name: Validate examples

on: [pull_request]

jobs:
  validate-json:
    name: Validate examples against Schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: |
          cd validation
          npm ci
          npm test
  json-formatting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

