name: Validate examples

on: [pull_request]

jobs:
  # get all frameworks in our repo
  get-frameworks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(find . -name '*_schema.json' ! -name 'base_schema.json' -printf "%h\n" | cut -c 3- | jq -R -s -c 'split("\n")[:-1]')"
  # loop over found frameworks
  verify-json-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        frameworks: ${{ fromJson(needs.get-frameworks.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./${{ matrix.frameworks }}/${{ matrix.frameworks }}_schema.json
          json_path_pattern: ./${{ matrix.frameworks }}/examples/.*.json$
